//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorkogo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы_подробно
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы_подробно()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public double Индентификатор { get; set; }
        public string Код_заказа { get; set; }
        public System.DateTime Дата_создания { get; set; }
        public System.DateTime Время_заказа { get; set; }
        public double Код_клиента { get; set; }
        public string Услуги { get; set; }
        public string Статус { get; set; }
        public Nullable<System.DateTime> Дата_закрытия { get; set; }
        public double Время_проката { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
    }
}
