//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gorkogo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public double Индентификатор { get; set; }
        public string Код_заказа { get; set; }
        public double Услуги { get; set; }
        public double Код_клиента { get; set; }
    
        public virtual Заказы_подробно Заказы_подробно { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Услуги Услуги1 { get; set; }
    }
}
